version: "2"

services:
    db:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - ./groupagreebot_database_05_05_2019.sql:/docker-entrypoint-initdb.d/init.sql
            - mysql-data:/var/lib/mysql/
        environment:
            MYSQL_USER: gab
            MYSQL_PASSWORD: gab
            MYSQL_DATABASE: groupagreebot_beta
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"

    groupagree:
        build: .
        stop_grace_period: 1s
        restart: unless-stopped
        depends_on:
            - db
        environment:
            GROUPAGREE_DB_HOST: db

    adminer:
        image: adminer
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - 8080:8080

volumes:
    mysql-data:
